name: checkmate
favicon: null
layout_spectrum: 0.6648130279500037
typography_spectrum: 0.16604471066966653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c3b4f'
    - '#405f73'
    - '#648290'
    - '#bfced5'
    - '#88a0ac'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
